markdown: redcarpet
highlighter: pygments
excerpt_separator: ""

# google_analytics_id:

repository: https://github.com/rubicus

timezone: Europe/Stockholm

name: "Rubicus' blog"
description: A blog about electronics, development and other stuff I feel fit in
url: rubicus.github.io

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: rubicus
