markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

# google_analytics_id: UA-50755011-1

repository: https://github.com/rubicus/jekyll
help_url: https://github.com/jekyll/jekyll-help

timezone: Europe/Stockholm

name: "Rubicus' blog"
description: A blog about electronics, development and other stuff I feel fit in
url: rubicus.github.io

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
